# $Id: Makefile,v 1.5 2006/11/26 13:04:40 source Exp source $
CC = gcc
CFLAGS = -g -W -Wall -O -fPIC -shared
LDFLAGS = -nostdlib -shared
LIBS = -lgcc -lc -ldl

all: libhttpcacheopen.so libhttpcacheopen.debug.so

libhttpcacheopen.so: wrapper.c md5.c cleanpath.c Makefile
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBS) wrapper.c

libhttpcacheopen.debug.so: wrapper.c md5.c cleanpath.c Makefile
	$(CC) -DDEBUG $(CFLAGS) $(LDFLAGS) -o $@ $(LIBS) wrapper.c

clean:
	rm -f libhttpcacheopen.debug.so libhttpcacheopen.so libhttpcacheopen.debug.so
