# $Id: Makefile,v 1.8 2008/04/20 10:31:32 source Exp source $
#
# Copyright 2006-2017 Niklas Edmundsson <nikke@acc.umu.se>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CC = gcc
CFLAGS = -std=c99 -g -W -Wall -O
LIBFLAGS = -fPIC -shared -DUSE_COPYD -nostdlib -shared
LDFLAGS = -lrt # for nanosleep on Solaris
LDFLAGS := $(LDFLAGS) -lsocket # for socket stuff on Solaris
LDFLAGS := $(LDFLAGS) -lsendfile # for sendfile*() on Solaris
LIBS = -lgcc -lc -ldl

all: libhttpcacheopen.so libhttpcacheopen.debug.so httpcachecopyd

libhttpcacheopen.so: wrapper.c md5.c cleanpath.c cacheopen.c config.h Makefile
	$(CC) $(CFLAGS) $(LIBFLAGS) $(LDFLAGS) -o $@ $(LIBS) wrapper.c

libhttpcacheopen.debug.so: wrapper.c md5.c cleanpath.c cacheopen.c config.h Makefile
	$(CC) -DDEBUG $(CFLAGS) $(LIBFLAGS) $(LDFLAGS) -o $@ $(LIBS) wrapper.c

httpcachecopyd: copyd.c cacheopen.c md5.c config.h Makefile
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ copyd.c

clean:
	rm -f libhttpcacheopen.debug.so libhttpcacheopen.so libhttpcacheopen.debug.so httpcachecopyd
