# $Id: Makefile,v 1.3 2006/11/20 17:36:05 source Exp source $
CC = gcc
CFLAGS = -g -W -Wall -O -fPIC -shared
LDFLAGS = -nostdlib -shared
LIBS = -lgcc -lc -ldl

all: libhttpcacheopen.so libhttpcacheopen.debug.so

libhttpcacheopen.so: httpcacheopen.c md5.c cleanpath.c Makefile
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBS) httpcacheopen.c

libhttpcacheopen.debug.so: httpcacheopen.c md5.c cleanpath.c Makefile
	$(CC) -DDEBUG $(CFLAGS) $(LDFLAGS) -o $@ $(LIBS) httpcacheopen.c

clean:
	rm -f *~ *.o core

realclean: clean
	rm -f libhttpcacheopen.so
